### ISSUE TITLE
Sidecar validation

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#154]
Over the past couple of weeks, @VisLab and I have discussed the procedure for validating sidecars as part of BIDS datasets. Here is the plan we came up with, slightly modified based on some thoughts I've had since then:

- Parse sidecars.
- Run syntax-only validation on all event sidecars, exiting on failure.
- Per TSV:
  - Find sidecars for that TSV, based on filename.
  - Parse TSV.
  - Run syntax-only validation on HED TSV column, skipping to next TSV on failure.
  - Parse and validate definitions.
  - Run semantic validation on sidecars and HED column, skipping to next TSV on failure of this or definition validation.
  - Substitute sidecar columns.
  - Run dataset validation on TSV.

**Comment by VisLab** [comment]
In bullet item 2, 

I think that there has to be more than syntax-only validation on all side cars.  I think it should actually check that tags that are not library tags are in the base schema.  This will cover 99.99% of the errors. 

I am wondering whether we shouldn't try to come up with a different way of declaring library schema so that we don't have to have them embedded in the files.  I don't have any ideas on this, but it would make things a lot easier..... thoughts?

**Comment by happy5214** [comment]
Since it appears we're going to be passing in the library schemas with the base schema version and not as definition tags (per https://github.com/hed-standard/hed-specification/issues/156), the separate passes are no longer necessary. Therefore, the new proposal is this:

- Parse sidecars.
- Run string-level validation on all event sidecars, exiting on any errors (not warnings).
- Per TSV:
  - Find sidecars for that TSV, based on filename.
  - Parse TSV.
  - Run string-level validation on HED TSV column, skipping to next TSV on failure.
  - Substitute sidecar columns.
  - Run event- and dataset-level validation (including definitions) on TSV.
