### ISSUE TITLE
Add support for "topLevelTagGroups"

### ISSUE THREAD

**Issue by IanCa** [hed-standard/hed-python#232]
topLevelTagGroup requires that the tag can only appear in a top-level tag group.  The tags that currently have this are:  Onset, Offset, Definition, and Event-context.  Without this restriction, the analysis becomes very complicated.
eg:
Valid (one def and nothing else) -> (definition/aslkadjfslk)
Invalid as it has two -> (onset, event-context/4)
Invalid (above top level) -> Onset

These should all always be unique in separte groups.  And they must be in a top level group
These will have an attribute for top level tag groups.

**Comment by VisLab** [comment]
We also just added another attribute tagGroup for tags.  The only tag that currently has it is Def-expand.  This attribute means that the tag must appear in the tag group.  @happy5214 and I agreed that a tag could not have both tagGroup and topLevelTagGroup attributes so that the validator doesn't give two messages if the tag misses them.   @IanCa the schema puts it in correctly, but it needs to be added to the validator.

**Comment by IanCa** [comment]
This is mostly implemented.
