### ISSUE TITLE
Remap works inconsistenly on integer columns

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-python#564]
When using the remap operation in the remodeler and one of the input columns contains integers, there is inconsistency between the online tool and the hed tools package on how these values should be represented in the remodeler json file.

For the HED web tools the operation works when the values are put in a strings, when hed python tools are installed, it works when they are integers.

The documentation does not specify how this case should be handled.

**Comment by VisLab** [comment]
@monique2208 Could you please retest using:
a) The [https://hedtools.ucsd.edu/hed_dev](https://hedtools.ucsd.edu/hed_dev).
b) The current version of hed-python develop branch.

The approach used is to internally convert remapping source keys to strings.  The destination mappings are not converted. 
Since the final output when written is a string, this shouldn't be a problem. 

However, if the remap operation is in the middle of a list of operations, this conversion may make a difference to downstream operations since the dataframe is not written out in this case.

We may have to more carefully implement this so that the types of the source columns of the dataframe aren't changed in the output. Please take a careful at this. It may be worth extracting the key columns and converting them without modifying them in the returned dataframe. What do you think?

**Comment by monique2208** [comment]
The issue is still the same. To remap integer columns using hed-python the input needs to be given in integers, while for the web tools the input needs to be given in strings. Otherwise both return the new column with only n/a's.

I also checked what happens when a remapped column is used as a source column. In this case the input for the second remap need to be strings. Even when the output of the remap was specified as integers, it needs to be specified as a string for the source column. I only tested this with the installed tools on command line. Note this is also inconsistent with the first remap operation, where the source column needs to be specified as an integer.

**Comment by monique2208** [comment]
Everything now works as expected, both on the web as in the command line. The remapping can be done using integers directly when specifying that the source column is an integer column, but it can also work when using strings. Only when integer and string representations are mixed in multiple remapping steps does it not work anymore but I think this is reasonable. The documentation is clear on how integer columns should be handeled.

**Comment by VisLab** [comment]
Fixed in develop branch.  Will be part of release hedtool 0.2.0
