### ISSUE TITLE
behavior of load_schema_version

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#834]
I think it should raise a `HedFileError`  rather than returning the latest version. We need to enforce specific versions going forward particularly because of partnered schemas.  @IanCa could you fix and do a PR.

**Comment by IanCa** [comment]
So we don’t want a function to load the latest version/version of library at all?This is the only place supporting that functionalityOn Jan 18, 2024, at 2:14 PM, Kay Robbins ***@***.***> wrote:﻿
I think it should raise a HedFileError  rather than returning the latest version. We need to enforce specific versions going forward particularly because of partnered schemas.  @IanCa could you fix and do a PR.

**Comment by VisLab** [comment]
Yes, I think we need to eliminate that behavior. Thanks
